# Image Node
FROM node:22-alpine

# Dossier de travail dans le container
WORKDIR /app

# Copier package.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le projet
COPY . .

# Exposer le port 5173 (Vite) ou 3000 (CRA)
EXPOSE 5173

# Commande par défaut
CMD ["npm", "run", "dev", "--", "--host"]
