# Image Node
FROM node:22-alpine AS build

WORKDIR /app

# Copier uniquement les dépendances
COPY package*.json ./

RUN npm install

# Copier juste le code source (pas toute la racine)
COPY src ./src
COPY public ./public
COPY index.html .
COPY vite.config.js .

# Build du frontend
RUN npm run build

# Image légère pour servir les fichiers
FROM nginx:alpine

# Copier le build final dans NGINX
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
