FROM node:22-alpine AS build

WORKDIR /app

# Copier le package.json ET package-lock.json du dossier FRONTEND
COPY package*.json ./

RUN npm install

# Copier tout le code source frontend
COPY . .

# Build du projet
RUN npm run build

# Image pour NGINX
FROM nginx:alpine

# Copier le build compilé
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
