services:

  mongodb:
    image: mongo:6
    container_name: codearena-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: codearena
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - internal-net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: codearena-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASS}
    depends_on:
      - mongodb
    networks:
      - internal-net
      


  backend:
    build: ./backend
    container_name: codearena-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongodb:27017/codearena?authSource=admin
    depends_on:
      - mongodb
    networks:
      - internal-net

  frontend:
    build: ./frontend
    container_name: codearena-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - internal-net



volumes:
  mongo-data:

networks:
  internal-net:
    driver: bridge
