version: '3.10'

services:
  mongodb:
    image: mongo:latest
    container_name: codearena-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: omar
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: codearena
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: codearena-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: omar
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - mongodb

  backend:
    build: .       # chemin vers ton Dockerfile
    container_name: codearena-backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://omar:12345@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb