# ---------------------------
# IMAGE DE BASE
# ---------------------------
FROM python:3.10-slim

# ---------------------------
# VARIABLES D'ENVIRONNEMENT
# ---------------------------
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# ---------------------------
# RÉPERTOIRE DE TRAVAIL
# ---------------------------
WORKDIR /app

# ---------------------------
# COPIE DES DÉPENDANCES
# ---------------------------
COPY requirements.txt .

# ---------------------------
# INSTALLATION DES DÉPENDANCES
# ---------------------------
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# ---------------------------
# COPIE DE TOUT LE CODE SOURCE
# ---------------------------
COPY . .

# ---------------------------
# EXPOSER LE PORT FASTAPI
# ---------------------------
EXPOSE 8000

# ---------------------------
# COMMANDE POUR DÉMARRER L'API
# ---------------------------
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

